### ISSUE TITLE
Provide data frame of operations without testing

### ISSUE THREAD

**Issue by noamross** [ropenscilabs/autotest#19]
So that users can see the operations that will be generated by `autotest()` before running, a function such as `autotest::generate_tests()` should provide the first four columns of the current `autotest()`.  This data frame can then be the input for `autotest::run_tests(), which would allow the user to append or filter a set of automatically-generated operations.

**Comment by mpadge** [comment]
Finished and closing with the `test` parameter in both `autotest_pacakge()` and `autotest()` functions, which gives results like these:

``` r
library (autotest)
x <- autotest_package (package = "stats", functions = "var", test = FALSE)

print (x)
#> # A tibble: 94 x 7
#>    type  fn_name parameter  parameter_type operation        content yaml_hash   
#>    <chr> <chr>   <chr>      <chr>          <chr>            <chr>   <chr>       
#>  1 dummy var     x          integer vector Integer vector … <NA>    bcf42b882bb…
#>  2 dummy var     x          generic vector Custom class de… <NA>    bcf42b882bb…
#>  3 dummy var     x          generic vector Convert vector … <NA>    bcf42b882bb…
#>  4 dummy var     na.rm      single logical Negate default … <NA>    bcf42b882bb…
#>  5 dummy var     na.rm      single logical Substitute inte… <NA>    bcf42b882bb…
#>  6 dummy var     na.rm      single logical Substitute char… <NA>    bcf42b882bb…
#>  7 dummy var     na.rm      single logical Length 2 vector… <NA>    bcf42b882bb…
#>  8 dummy var     (return o… <NA>           Check that desc… <NA>    bcf42b882bb…
#>  9 dummy var     (return o… <NA>           Check whether d… <NA>    bcf42b882bb…
#> 10 dummy var     (return o… <NA>           Compare class o… <NA>    bcf42b882bb…
#> # … with 84 more rows

table (x$type)
#> 
#> dummy 
#>    94
```

<sup>Created on 2020-12-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

That lists all (current) 94 tests which would be applied to `stats::var()`, without actually applying them. Runs by default for an entire package, which for `stats` lists 4,952 tests for 225 function aliases.
