### ISSUE TITLE
Expose a function to print/return all operations that exist

### ISSUE THREAD

**Issue by noamross** [ropenscilabs/autotest#20]
Available operations should exist not as blocks of codes within functions, but as functions or other standard objects themselves so that they can be combined into lists, manipulated and passed as arguments. For instance, `generate_tests()` could by default use all available operations (at least those compatible with different argument types), but take an argument `operations = ` which would accept a list of functions of `operation` type objects

As part of this there should be a functionin the package that returns a list or data frame of available operations.  This might include metadata like descriptions or types that are compatible with the operations.

**Comment by mpadge** [comment]
``` r
library (autotest)
autotest_types ()
#> # A tibble: 15 x 6
#>    type  fn_name parameter parameter_type   operation        content            
#>    <chr> <chr>   <chr>     <chr>            <chr>            <chr>              
#>  1 dummy <NA>    <NA>      rectangular      Convert one rec… "check for error/w…
#>  2 dummy <NA>    <NA>      rectangular      Convert one rec… "expect dimensions…
#>  3 dummy <NA>    <NA>      rectangular      Convert one rec… "expect column nam…
#>  4 dummy <NA>    <NA>      rectangular      Convert one rec… "expect all column…
#>  5 dummy <NA>    <NA>      rectangular      Extend existent… "(Should yield sam…
#>  6 dummy <NA>    <NA>      rectangular      Replace class w… "(Should yield sam…
#>  7 dummy <NA>    <NA>      vector           Convert vector … "(Should yield sam…
#>  8 dummy <NA>    <NA>      vector           Custom class de… "(Should yield sam…
#>  9 dummy <NA>    <NA>      numeric          Add trivial noi… "(Should yield sam…
#> 10 dummy <NA>    <NA>      single integer   Integer value c… "(Should yield sam…
#> 11 dummy <NA>    <NA>      single character Change case      "(Should yield sam…
#> 12 dummy <NA>    <NA>      single integer   Ascertain permi… "Should either be …
#> 13 dummy <NA>    <NA>      single integer   Length 2 vector… "Should trigger me…
#> 14 dummy <NA>    <NA>      single logical   Negate default … "(Function call sh…
#> 15 dummy <NA>    <NA>      single name or … Unquoted name/f… "Capture any warni…
```

<sup>Created on 2021-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

That's exactly the same class object returned from all tests, and so will enable an additional `test` column to be set to `FALSE` to switch off any tests when passed as input object via #34.

All tests are S3 methods, so can easily be extended to include user-specified tests.

**Comment by mpadge** [comment]
Re-opening because the list does not currently include tests of return objects.
